apiVersion: v1
kind: ResourceQuota
metadata:
  name: env-quota
  labels:
    {{- include "fm-dev-platform.commonLabels" (dict "root" $ "deploymentName" "env-quota") | nindent 4 }}
  annotations:
    {{- include "fm-dev-platform.commonAnnotations" (dict "root" $) | nindent 4 }}
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "4"
    requests.memory: 12Gi
    limits.memory: 12Gi
